-- 1. 사원번호가 176인 사원의 LAST_NAME, 부서번호 정보 조회
SELECT LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 176;
-- 2. 급여가 12000 이상 되는 직원들의 LAST_NAME, 급여 조회
SELECT LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY >= 12000;
-- 3. 급여 5000~12000 범위가 아닌 사람들의 LAST_NAME, 급여 조회
SELECT LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY < 5000 OR SALARY > 12000;
-- 4. 20, 50번 부서에 근무하는 사원들의 LAST_NAME, 부서번호를 오름차순으로 조회
SELECT LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID IN (20, 50) ORDER BY DEPARTMENT_ID, LAST_NAME;
-- 5. 커미션을 받는 모든 사원들의 LAST_NAME, 급여, 커미션 조회. 급여 내림차순, 커미션 내림차순 조회
SELECT
	LAST_NAME,
	SALARY,
	COMMISSION_PCT
FROM
	EMPLOYEES
WHERE
	COMMISSION_PCT IS NOT NULL
ORDER BY
	SALARY DESC,
	COMMISSION_PCT DESC;
SELECT
	LAST_NAME,
	SALARY,
	COMMISSION_PCT
FROM
	EMPLOYEES
WHERE
	COMMISSION_PCT > 0
ORDER BY
	SALARY DESC,
	COMMISSION_PCT DESC;
-- 6. 연봉이 2500, 3500, 7500이 아니며 직무가 SA_REP, ST_CLERK인 사원 조회
SELECT
	*
FROM
	EMPLOYEES
WHERE
	SALARY NOT IN (2500, 3500, 7500)
	AND JOB_ID IN ('SA_REP', 'ST_CLERK');
-- 7. 2015/02/20 ~ 05/01 사이에 고용된 사원들의 LAST_NAME, 사번, 고용일자 조회. 고용일자 내림차순
SELECT
	LAST_NAME,
	EMPLOYEE_ID,
	HIRE_DATE
FROM
	EMPLOYEES
WHERE
	HIRE_DATE >= '2015-02-20'
	AND HIRE_DATE <= '2015-05-01'
ORDER BY
	HIRE_DATE DESC;
-- 8. 20, 50번 부서에 근무하는 사원들 중에서 연봉이 5000 이상 12000 이하인 사원들의 LAST_NAME, 급여 조회. 급여 오름차순
SELECT
	LAST_NAME,
	SALARY
FROM
	EMPLOYEES
WHERE
	DEPARTMENT_ID IN (20, 50)
	AND SALARY BETWEEN 5000 AND 12000
ORDER BY
	SALARY; 
-- 9. 연봉이 5000 이상 12000 이하가 아닌 사원들의 LAST_NAME, 급여 조회. 급여 오름차순
SELECT
	LAST_NAME,
	SALARY
FROM
	EMPLOYEES
WHERE
	DEPARTMENT_ID IN (20, 50)
	AND SALARY NOT BETWEEN 5000 AND 12000
ORDER BY
	SALARY; 
-- 10. 2015/02/20 ~ 05/01 사이에 고용된 사원들의 LAST_NAME, 사번, 고용일자 조회. 고용일자 내림차순
SELECT
	LAST_NAME,
	EMPLOYEE_ID,
	HIRE_DATE
FROM
	EMPLOYEES
WHERE
	HIRE_DATE BETWEEN '2015/02/20' AND '2015/05/01'
ORDER BY
	HIRE_DATE DESC; 
-- 11. LAST_NAME에 u가 포함되는 사원들의 사번, LAST_NAME 조회
SELECT
	EMPLOYEE_ID,
	LAST_NAME
FROM
	EMPLOYEES
WHERE
	LAST_NAME LIKE '%u%';
-- 12. LAST_NAME에 4번째 글자가 a인 사원들의 LAST_NAME 조회
SELECT
	LAST_NAME
FROM
	EMPLOYEES
WHERE
	LAST_NAME LIKE '___a%';
-- 13. LAST_NAME에 a 혹은 e글자가 있는 사원들의 LAST_NAME 조회(라네 오름차순)
SELECT
	LAST_NAME
FROM
	EMPLOYEES
WHERE
	LAST_NAME LIKE '%a%'
	OR LAST_NAME LIKE '%e%'
ORDER BY
	LAST_NAME;
-- 14. LAST_NAME에 a와 e글자가 포함된 사원들의 LAST_NAME을 조회(오름차순)
SELECT
	LAST_NAME
FROM
	EMPLOYEES
WHERE
	LAST_NAME LIKE '%a%'
	AND LAST_NAME LIKE '%e%'
ORDER BY
	LAST_NAME;
-- 15. 매니저 아이디가 없는 사원들의 LAST_NAME, JOB_ID 조회
SELECT
	LAST_NAME,
	JOB_ID
FROM
	EMPLOYEES
WHERE
	MANAGER_ID IS NULL;
-- 16. 직무가 ST_CLERK인 사원이 근무하고 있지 않은 부서 ID 조회(단, 부서번호가 NULL은 제외)
SELECT
	DEPARTMENT_ID
FROM
	EMPLOYEES
WHERE
	JOB_ID != 'ST_CLERK' AND DEPARTMENT_ID IS NOT NULL;
-- 17. COMMISSION_PCT가 NULL이 아닌 사원들 중에서 COMMISSION = SALARY * COMMISSION_PCT를 구하여 사번, FIRST_NAME_ JOB_ID 조회
SELECT
	SALARY * COMMISSION_PCT AS COMMISSION,
	EMPLOYEE_ID,
	FIRST_NAME,
	JOB_ID
FROM
	EMPLOYEES
WHERE
	COMMISSION_PCT IS NOT NULL;