-- department(학과)
-- 학과코드(dept_id), 학과명(dept_name, not null)
CREATE TABLE DEPARTMENT(
DEPT_ID VARCHAR2(4) CONSTRAINT DEPARTMENT_DEPTID_PK PRIMARY KEY, 
DEPT_NAME VARCHAR2(40) NOT NULL);

INSERT INTO DEPARTMENT VALUES('A001', '데이터사이언스');
INSERT INTO DEPARTMENT VALUES('A002', '경영학과');

-- student(학생)
-- 학번(student_id), 이름(name), 키(height), 학과코드(dept_id)
CREATE TABLE STUDENT(
STUDENT_ID VARCHAR2(8) CONSTRAINT STUDENT_STUDENTID_PK PRIMARY KEY, 
NAME VARCHAR2(20),
HEIGHT NUMBER(4, 1),
DEPT_ID VARCHAR2(4) REFERENCES DEPARTMENT(DEPT_ID) ON DELETE CASCADE);

INSERT INTO STUDENT VALUES('20250001', '홍길동', 163.5, 'A001');
INSERT INTO STUDENT VALUES('20250002', '성춘향', 155.7, 'A002');

--professor(교수)
-- 교수코드(prof_id), 교수명(prof_name), 학과코드(dept_id)
CREATE TABLE PROFESSOR(
PROF_ID VARCHAR2(4) CONSTRAINT PROFESSOR_PROFID_PK PRIMARY KEY, 
PROF_NAME VARCHAR2(20),
DEPT_ID VARCHAR2(4) REFERENCES DEPARTMENT(DEPT_ID) ON DELETE CASCADE);

INSERT INTO PROFESSOR VALUES('P001', '김유진', 'A001');

--subject(과목)
-- 과목코드(subj_id), 과목명(subj_name), 시작일(start_date), 종료일(end_date), 교수코드(prof_id)
CREATE TABLE SUBJECT(
SUBJ_ID VARCHAR2(4) CONSTRAINT SUBJECT_SUBJID_PK PRIMARY KEY, 
SUBJ_NAME VARCHAR2(40),
START_DATE DATE,
END_DATE DATE,
PROF_ID VARCHAR2(4) REFERENCES PROFESSOR(PROF_ID) ON DELETE CASCADE);

INSERT INTO SUBJECT VALUES('S001', '파이썬', '2025-03-01', '2025-06-30', 'P001');

--enrollment(수강)
-- 수강코드(enroll_id), 수강일자(enroll_date), 학번(student_id), 과목코드(subj_id)
CREATE SEQUENCE SEQ_ENROLLMENT_ENROLLID
INCREMENT BY 1
START WITH 1
NOMAXVALUE 
MINVALUE 1
NOCYCLE;

CREATE TABLE ENROLLMENT(
ENROLL_ID NUMBER(4) CONSTRAINT ENROLLMENT_ENROLLID_PK PRIMARY KEY, 
STUDENT_ID VARCHAR2(8) REFERENCES STUDENT(STUDENT_ID) ON DELETE CASCADE,
SUBJ_ID VARCHAR2(4) REFERENCES SUBJECT(SUBJ_ID) ON DELETE CASCADE,
ENROLL_DATE DATE);

INSERT INTO ENROLLMENT VALUES(SEQ_ENROLLMENT_ENROLLID.NEXTVAL, '20250001', 'S001', '2025-06-30');